events {}

http {
    server {
        listen 80;

        # Auth Service
        location /api/auth/ {
            proxy_pass http://auth-service:3001/;
        }

        # Product Service
        # location /api/products/ {
        #     proxy_pass http://products-service:3003/;
        # }
    }
}