events {}

http {
    server {
        listen 80;

        # Frontend - just use the index.js file to show hello world
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        # Auth Service
        location /api/auth/ {
            proxy_pass http://auth-service:3001/;
        }

        # Product Service
        location /api/products/ {
            proxy_pass http://products-service:3003/;
        }

        # Notification Service
        location /api/notification/ {
            proxy_pass http://notification-service:3004/;
        }

        # Cart Service
        location /api/cart/ {
            proxy_pass http://cart-service:3004/;
        }
    }
}