services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env.prod
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "3002:3002"
    env_file:
      - ./notification-service/.env.prod
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq:
        condition: service_healthy

  products-service:
    build:
      context: ./products-service
    ports:
      - "3003:3003"
    env_file:
      - ./products-service/.env.prod
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  cart-service:
    build:
      context: ./cart-service
    ports:
      - "3004:3004"
    env_file:
      - ./cart-service/.env.prod
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  order-service:
    build:
      context: ./order-service
    ports:
      - "3005:3005"
    env_file:
      - ./order-service/.env.prod
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq:
        condition: service_healthy

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "3006:3006"
    env_file:
      - ./payment-service/.env.prod
    environment:
      - NODE_ENV=production
    depends_on:
      rabbitmq:
        condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./api-gateway/index.html:/usr/share/nginx/html/index.html
    depends_on:
      - auth-service
      - notification-service
      - products-service
      - cart-service

volumes:
  redis_data: