apiVersion: v1
kind: Service

metadata:
  name: product-service-svc
  namespace: nexcart

spec:
  selector:
    app: product-service

  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003

  type: ClusterIP
