apiVersion: v1
kind: Service

metadata:
  name: order-service-svc
  namespace: nexcart

spec:
  selector:
    app: order-service

  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005

  type: ClusterIP
