apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment
  namespace: nexcart

spec:
  revisionHistoryLimit: 0
  replicas: 5

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: shresth2725/frontend:55

          ports:
            - containerPort: 80

          envFrom:
            - secretRef:
                name: frontend-secret
