- hosts: master
  become: yes

  tasks:

    - name: Initialize Kubernetes cluster
      shell: |
        kubeadm init --pod-network-cidr=192.168.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy admin.conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu

    - name: Install Calico network plugin
      become_user: ubuntu
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.28.0/manifests/calico.yaml

    - name: Generate join command
      shell: kubeadm token create --print-join-command
      register: join_command

    - name: Save join command
      set_fact:
        kube_join_command: "{{ join_command.stdout }}"

    - name: Install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone NexCart repository
      become_user: ubuntu
      git:
        repo: 'https://github.com/Shresth2725/NexCart.git'
        dest: /home/ubuntu/NexCart
        update: yes

    - name: Copy secret files to master node
      copy:
        src: "../kubernetes/{{ item }}/secret.yml"
        dest: "/home/ubuntu/NexCart/kubernetes/{{ item }}/secret.yml"
        owner: ubuntu
        group: ubuntu
        mode: '0600'
      loop:
        - auth-service
        - cart-service
        - notification-service
        - order-service
        - payment-service
        - product-service