- hosts: workers
  become: yes

  tasks:

    - name: Join workers to cluster
      shell: |
        {{ hostvars['k8s-master']['kube_join_command'] }}
      args:
        creates: /etc/kubernetes/kubelet.conf

    - name: Label worker node
      delegate_to: k8s-master
      become: yes
      become_user: ubuntu
      shell: |
        kubectl label node {{ ansible_hostname }} node-role.kubernetes.io/worker=worker --overwrite